general:
  kafka-topic: transactions

incentive:
  api:
    url: http://localhost:8080/incentive

server:
  port: 33400

spring:
  kafka:
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jpmc.midascore.foundation
        
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:midasdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console 